apiVersion: postgres.vibhordubey.com/v1alpha1
kind: PostgresDatabase
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-go
    app.kubernetes.io/managed-by: kustomize
  name: postgresdatabase-sample
spec:
  databaseName: "sampledb"
  storage:
    size: "1Gi"
    storageClass: "standard"
